### ISSUE TITLE
SSO: get_profile/2 with a string argument raises MatchError

### ISSUE THREAD

**Issue by newt-beach** [workos/workos-elixir#40]
### Environment

* Elixir version (elixir -v): 1.14.1
* Erlang/OTP version (erl): 25

### Description
I'm able to authenticate with SSO, but in the success callback, invoking `WorkOS.SSO.get_profile/2` with the access token returned from `get_profile_and_token/2` throws an error.
### Expected Behavior

```
# in my redirect, after getting a code back from WorkOS
{:ok, %{"access_token" => access_token}} = WorkOS.SSO.get_profile_and_token(code) // "01HE0PDDJQ8SDPFS12REEPNBXJ"
WorkOS.SSO.get_profile(access_token)  // Profile is returned
```

### Actual Behavior

```
# in my redirect, after getting a code back from WorkOS
{:ok, %{"access_token" => access_token}} = WorkOS.SSO.get_profile_and_token(code) // "01HE0PDDJQ8SDPFS12REEPNBXJ"
WorkOS.SSO.get_profile(access_token) 

 (MatchError) no match of right hand side value: "01HE0PDDJQ8SDPFS12REEPNBXJ"
        (workos 0.2.0) lib/workos/api.ex:13: WorkOS.API.client/1
        (workos 0.2.0) lib/workos/api.ex:32: WorkOS.API.get/3
```

<img width="768" alt="image" src="https://github.com/workos/workos-elixir/assets/3690795/4f86420b-71e5-4847-b460-a9a0ca1aa84f">
 
### Steps to Reproduce
1. get access token from `get_profile_and_token/2` with no options passed
2. invoke `get_profile/2` with this token, and no other options passed

Thank you for this repo ✌️

**Comment by LauraBeatris** [comment]
Hey @newt-beach, thanks for raising the issue! We're taking a look at that and will get back to you soon.

**Comment by LauraBeatris** [comment]
@newt-beach Could you please confirm which package version are you using? I wasn't able to repro on my side using the `0.3.0`

**Comment by newt-beach** [comment]
Hey @LauraBeatris, turns out I was on `0.2.0` 🤦‍♂️🤦‍♂️. After upgrading to `0.3.0` I am able to fetch the profile. Appreciate your help!

**Comment by LauraBeatris** [comment]
> Hey @LauraBeatris, turns out I was on `0.2.0` 🤦‍♂️🤦‍♂️. After upgrading to `0.3.0` I am able to fetch the profile. Appreciate your help!

Hey @newt-beach, glad you are able to fetch the profile now! The reason for you to be using `0.2.0` was prob because our `README.md` wasn't displaying the latest version and we've just updated it!
